version: "3.9"

services:

  db:
    image: postgres
    restart: always
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
    environment:
      # Default user, postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: helloworld
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081